---
 # directory configuration
 cluster_file_dir: "../data/clusters_after_remove_files_with_no_popsa.yaml"
 pocket_dir: "../data/googlenet-dataset/"
 pop_dir: "../data/pops-googlenet/"
 trained_model_dir: "../trained_models/"
 loss_dir: "./results/"
 confusion_matrix_dir: "./results/"

 # dataset configuration
 merge_info: [[0, 9, 12, 25], 2, [3, 8, 13, 27], 4, 6, [7, 19, 21], [10, 16, 28], 15, 17, 18, [20, 23], 24, 26, 29]
 features_to_use: ['x', 'y', 'z', 'r', 'theta', 'phi', 'sasa', 'charge', 'hydrophobicity', 'binding_probability', 'sequence_entropy']   

 # model configuration 
 which_model: 'jknwm' # 'jk', 'residual', 'pna', 'jknwm', 'jkgin' or 'normal'
 model_size: 128 # size of the neural network
 num_layers: 6
 num_channels: 3 # number of neural message masking channels form jknmm

 # loss configuration
 which_loss: 'Focal' # 'CrossEntropy' or 'Focal'
 use_class_weights: False
 initial_focal_gamma: 0
 focal_gamma_ascent: True
 focal_gamma_ascent_epoch: [25, 100, 170] # gamma = 1, 2, 3

 # train configuration
 num_epoch: 100
 lr_decay_epoch: [100, 170]
 batch_size: 256
 learning_rate: 0.003
 weight_decay: 0.0007




